zookeeper:
  image: nano/zookeeper:latest
  ports: 
    - "2181:2181"
#kafka-client-test:
#  image: nano/kafka:0.9.0.0
#  links:
#    - kafka:kafka
kafka:
  #build: .
  image: nano/kafka:0.8.2.2
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.10.1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
